
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8888:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer_network

  portainer-init:
    image: curlimages/curl:latest
    container_name: portainer-init
    depends_on:
      - portainer
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    entrypoint: |
      /bin/sh -c '
        echo "Waiting for Portainer to be ready...";
        until curl -s http://portainer:9000/api/system/status >/dev/null; do
          sleep 5;
        done;

        echo "Attempting to initialize Portainer admin user...";
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" \
          -d "{\"Username\":\"admin\",\"Password\":\"$$ADMIN_PASSWORD\"}" \
          http://portainer:9000/api/users/admin/init)

        if [ "$$HTTP_CODE" = "200" ] || [ "$$HTTP_CODE" = "409" ]; then
          echo "✅ Done: Admin user initialized or already exists.";
        else
          echo "❌ Failed to initialize admin user. Status: $$HTTP_CODE";
        fi
      '
    networks:
      - portainer_network
    restart: "no"

volumes:
  portainer_data:

networks:
  portainer_network:
    driver: bridge
